---
title: "Diagnosing the conservative PICP"
format: 
  html:
    embed-resources: true
---

## Sanity-check: frequentist linear regression

```{r, echo = F}
library(tidyverse) |> suppressPackageStartupMessages()
library(targets) |> suppressPackageStartupMessages()
library(here) |> suppressPackageStartupMessages()
```

Fitting frequentist regression models needs to be outside the pipeline because the pipeline uses `stantargets`. (???)

```{r}
# import data objects from the pipeline
obj  <- tar_objects(store = here("_targets"))
obj  <- obj[grepl("mcmc_data_", obj)]

# allocating memory for a for-loop (not very tidy, I know :-))
# translate to map_ later
N    <- length(obj)
n    <- length(tar_read_raw(obj[1], store = here("_targets")))
Ntot <- N * n
results <- data.frame(
  rep         = vector("character", Ntot),
  subrep      = vector("numeric", Ntot),
  sample_size = vector("numeric", Ntot),
  tau         = vector("numeric", Ntot),
  tails       = vector("character", Ntot),
  PICP = vector("numeric", Ntot)
)

# fit-and-predict
fit_predict_flinreg <- function(tarobj) {
  flinreg <- lm(y_obs ~ x_obs, data = tarobj)
  preds <- predict(
    flinreg, newdata = tarobj$validation_data,
    interval = "prediction"
  ) %>% as.data.frame()
  PICP <- mean(
    between(tarobj$validation_data$y_obs, preds$lwr, preds$upr)
  )
  return(PICP)
}

a <- 1
for (i in seq_along(obj)) {
  data_list <- tar_read_raw(obj[i], store = here("_targets"))
  scenario  <- stringr::str_split(obj[i],"_")[[1]]
  for (j in seq_along(data_list)) {
    results$rep[a]         <- scenario[6]
    results$sample_size[a] <- as.numeric(gsub("[^0-9.]", "", scenario[3]))
    results$tau[a]         <- as.numeric(gsub("[^0-9.]", "", scenario[4]))
    results$tails[a]       <- substr(scenario[5], 5, nchar(scenario[5]))
    results$subrep[a] <- j
    data_sublist      <- data_list[[j]]
    results$PICP[a]   <- fit_predict_flinreg(data_sublist)
    a <- a + 1
  }
}
rm(i, j, a, data_list, data_sublist)
```

@fig-results shows the results: the PICP stays overly conservative.

```{r, echo=FALSE}
#| label: fig-results
#| fig-cap: "Summary of the results"

results %>%
  ggplot(aes(factor(tau), PICP, color = tails)) +
  facet_wrap(~ sample_size) +
  geom_boxplot() +
  geom_jitter(position = position_jitterdodge(jitter.height = 0,
                                              jitter.width = .2)) +
  geom_hline(yintercept = .95, lty = 2)
```


